# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - othello-core/*
      - othello-gui/*

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
    displayName: 'Install Node.js'

  - script: |
      cd ./othello-core
      yarn
    displayName: 'Install core dependencies'

  - script: |
      cd ./othello-gui
      yarn
      cd ../othello-core
      yarn build:gui
    displayName: 'Install dependencies'

  - script: |
      cd ./othello-gui
      yarn build
    displayName: 'Build'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'build'
      ArtifactName: 'drop'
      publishLocation: 'Container'